apiVersion: v1
kind: Service
metadata:
  name: ci-cd-app-service
  labels:
    app: ci-cd-app
spec:
  type: NodePort
  selector:
    app: ci-cd-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080  # Access at localhost:30080
